### ISSUE TITLE
add header-line face

### ISSUE THREAD

**Issue by kaiwk** [ianpan870102/vscode-default-dark-emacs-theme#10]
`header-line` inherit from `mode-line` by default, so modifing `mode-line` has side effects to `header-line`, see:

- https://github.com/kiennq/emacs-mini-modeline/issues/39#issue-686382474
- https://github.com/bbatsov/zenburn-emacs/blob/6ca85d248468639650fcce2c2d13c46c6e99ded3/zenburn-theme.el#L177

**Comment by ianyepan** [comment]
Thanks for pointing this out @kaiwk! Could you provide one example where header-line is used, and also if it's bad that we keep it the same as mode-line? Just trying to decide if I should give header-line its own face declaration.

**Comment by kaiwk** [comment]
AFAIK, any mode derived from `tabulated-list-mode` will use `header-line` to show table head, such as `package-menu-mode`(triggered by `list-package`).

I think in most case it will be fine, except when someone want to heavily customize `mode-line`, for example, set mode line height to '0.1'. it seems many other themes tend to set `header-line`:

- monokai: https://github.com/oneKelvinSmith/monokai-emacs/blob/4281fc13dadef98942c8d43024de024f2392fec5/monokai-theme.el#L603
- cyberpunk: https://github.com/n3mo/cyberpunk-theme.el/blob/cbd0d7193e69ff9e98262eb06aee3d27667ff5f5/cyberpunk-theme.el#L125
- leuven: https://github.com/fniessen/emacs-leuven-theme/blob/a116202c82613c087440d2e8a6a504b08f1862ce/leuven-theme.el#L213

**Comment by ianyepan** [comment]
I see. Let me try to declare header-line separately so users' customization of mode-line won't affect header-line.

**Comment by ianyepan** [comment]
Hi @kaiwk, I just fixed it in the following commit: https://github.com/ianpan870102/vscode-dark-plus-emacs-theme/commit/1e694e1704e6bf55726040953ed5cf703f02c16d
Closing issue for now, and thx again for bringing this up 👍
