### ISSUE TITLE
Add support for emacs 27+ tabs

### ISSUE THREAD

**Issue by ghost** [ianpan870102/vscode-default-dark-emacs-theme#13]
Emacs 27 tabs/tab-line look bad without explicit styling. Centaur tabs also makes use of the native tabs and looks bad in 27+ without support.
Faces are:
tab-line
tab-bar
tab-bar-tab
tab-bar-tab-inactive

**Comment by ianyepan** [comment]
Support added in latest commit. Feel free to reopen if you see anything that could be improved.

**Comment by ghost** [comment]
Looks like tab-line is needed as well. I still have a light gray background for the part of the tab-line that doesn't have any tabs.

**Comment by ianyepan** [comment]
Hi @dm19 thanks for getting back. Do you mind attaching a screenshot of the effects of "tab-line"?

**Comment by ghost** [comment]
No problem.

No customization: 
![doom-tabs-2](https://user-images.githubusercontent.com/31514792/111940573-7c06f600-8aa5-11eb-9bba-27fc76a21fd1.png)
![doom-tab-3](https://user-images.githubusercontent.com/31514792/111940582-81644080-8aa5-11eb-89e8-0da18977f465.png)

Customized tab-line (just realized that's not the right color to match vscode, but still shows the change):
![doom-tabs-1](https://user-images.githubusercontent.com/31514792/111940621-92ad4d00-8aa5-11eb-970e-f8aa8f6abf47.png)

**Comment by ianyepan** [comment]
I just added faces for tab-line too. Let me know if this is working as expected!

**Comment by brownts** [comment]
I ran across a few additional face configurations that are missing from 27.x as well as 28.x for tab-line and should be configured differently (to be useful) from their defaults:
- tab-line-tab-current
- tab-line-tab-inactive
- tab-line-tab-inactive-alternate

![tab-line-tab-faces](https://user-images.githubusercontent.com/17529295/200483255-72cb3be1-2e08-4416-ad48-18ff9e8ab471.png)
![tab-line-tab-faces-2](https://user-images.githubusercontent.com/17529295/200483262-70d5e61f-d7b7-426d-9a82-b95e49da6e49.png)

**Comment by ianyepan** [comment]
If you could provide a pull request, I'd be more than happy to merge it! Thanks.
