### ISSUE TITLE
Add styling for window divider mode

### ISSUE THREAD

**Issue by ghost** [ianpan870102/vscode-default-dark-emacs-theme#14]
Doom emacs uses window divider mode to draw the borders between windows. The default color is considerably brighter than vscode dark+'s window borders.
Faces:
- window-divider
- window-divider-first-pixel
- window-divider-last-pixel

**Comment by ianyepan** [comment]
I've darkened the window dividers in the latest commit (https://github.com/ianpan870102/vscode-dark-plus-emacs-theme/commit/2c258ec6c921682c81c83ad3545db1d792d9ec10), thanks for opening the issue.
