### ISSUE TITLE
Add solaire-line-number-face

### ISSUE THREAD

**Issue by ghost** [ianpan870102/vscode-default-dark-emacs-theme#15]
I'm assuming the intent is to keep line numbers with the #1e1e1e background. Solaire mode seems to change them to the #252526 background color.

**Comment by ghost** [comment]
Actually it looks like defining line-number's background instead of setting it to nil is what's needed to work with solaire mode, not adding solaire-line-number-face.

**Comment by ianyepan** [comment]
Please send a pull request if you have a solution. (btw, this theme is not recommended to work with solaire-mode yet)

**Comment by ghost** [comment]
I'm assuming solaire-mode support is an eventual goal since it enhances the vscode emulation so much and looks so good on Wilmersdorf. :smile: 

 It looks like there are a few faces that might need tweaked to play well with solaire-mode (maybe the issue title should be edited?). I will use the theme for a while with solaire-mode to try to catch as many as I can at once. The screenshots I took for #13 show some of the customization I'm using for solaire-mode at the moment. 

![doom-tabs-1](https://user-images.githubusercontent.com/31514792/111941399-5b3fa000-8aa7-11eb-870d-55a66b418a47.png)

**Comment by ianyepan** [comment]
Fair enough haha. I'll see what I can do.

**Comment by ianyepan** [comment]
I'm not sure what's going on with solaire-mode ... no matter if I set solaire-mode-auto-swap-bg to `t` or `nil`, the background colors are not the one I originally designed it.

I want the coding buffer bg to be `#1E1E1E` no matter what. The secondary color should be `#252526` for neotree, vterm, magit etc.

But now I am having a lighter background in the coding panel...

![image](https://user-images.githubusercontent.com/36686900/112723984-21a9e180-8f4c-11eb-8725-27b61dbb6d07.png)

**Comment by ianyepan** [comment]
I believe the behaviour wasn't like this before. I've opened an issue at solaire-mode here: https://github.com/hlissner/emacs-solaire-mode/issues/40

**Comment by ianyepan** [comment]
Solved in latest commit!
