### ISSUE TITLE
Customization options

### ISSUE THREAD

**Issue by Murgalha** [ianpan870102/vscode-default-dark-emacs-theme#16]
Hello,

I have added a few customization options on the theme, based on others that have that style, such as [Solarized](https://github.com/bbatsov/solarized-emacs).
As an example, I added `dark-plus-box-org-todo` to remove the border square on the todo keyword (default values are set to keep the theme as-is). Are you interested in these options? Can I make a PR?

Changes: https://github.com/Murgalha/vscode-dark-plus-emacs-theme/commit/e4b5101b57ed66c17b2d1f1bf7def60e4a278926

**Comment by ianyepan** [comment]
Absolutely, PRs welcome!

**Comment by ianyepan** [comment]
@Murgalha Just one issue: could you rename the variable names to start with "vscode-dark-plus..." instead of just "dark-plus..."? Otherwise it won't pass some linting tests.

**Comment by Murgalha** [comment]
I changed the variable names and updated the README as well.
Also opened the PR #17

**Comment by ianyepan** [comment]
Awesome, thanks for the work!
