### ISSUE TITLE
Link broken in readme.md

### ISSUE THREAD

**Issue by abhijeetsrivastava** [ianpan870102/vscode-default-dark-emacs-theme#18]
link for https://github.com/ianpan870102/vscode-dark-emacs-theme is broken/not working.

Nice theme. Thanks!

**Comment by ianyepan** [comment]
Thanks for the heads-up! I'll remove the link -- due to low demand, that variant is no longer maintained.

**Comment by ianyepan** [comment]
Fixed in the latest commit
