### ISSUE TITLE
AUCTeX Support

### ISSUE THREAD

**Issue by schlasim** [ianpan870102/vscode-default-dark-emacs-theme#19]
When using [AUCTeX](https://www.gnu.org/software/auctex/) in Emacs, lots of colors remain unchanged and look horrible. See screenshot below.
![auctex](https://user-images.githubusercontent.com/7462005/113110162-0caca700-9207-11eb-91d0-0964dd4d981a.png)
Maybe you could modify the `font-latex-highlighting-faces`. See also [3.1.5 Faces used by font-latex](https://www.gnu.org/software/auctex/manual/auctex/Faces.html).

**Comment by ianyepan** [comment]
Just added a commit that solves this issue, thanks for bringing it up!
Don't hesitate to reopen this thread if you feel like I'm missing something :-)
