### ISSUE TITLE
Theme issue?

### ISSUE THREAD

**Issue by anildigital** [ianpan870102/vscode-default-dark-emacs-theme#20]
I am not sure if it's a theme issue or org mode issue. Words after underscore gets subscripted.

<img width="1194" alt="image" src="https://user-images.githubusercontent.com/266/114562618-4613f680-9c8c-11eb-9202-5393f6c4c832.png">

**Comment by ianyepan** [comment]
I'm guessing it's an org-mode design.

> I am not sure if it's a theme issue or org mode issue. 

Ah this is easy to tell -- what happens when you use another theme?

**Comment by anildigital** [comment]
@ianpan870102 Issue exists in other themes as well. Adding `#+OPTIONS: ^:nil` at the top of file fixes it.

**Comment by ianyepan** [comment]
Thanks for reporting! I believe it's safe to close this issue now. :-)
