### ISSUE TITLE
Tree-sitter giving error

### ISSUE THREAD

**Issue by elge70** [ianpan870102/vscode-default-dark-emacs-theme#22]
Error Message

Debugger entered--Lisp error: (error "Invalid face inheritance" "#c586c0")
  internal-set-lisp-face-attribute(tree-sitter-hl-face:keyword :inherit "#c586c0" #<frame  georgezack@GZDELL 00000000053fddd0>)
  set-face-attribute(tree-sitter-hl-face:keyword #<frame  georgezack@GZDELL 00000000053fddd0> :inherit "#c586c0")
  apply(set-face-attribute tree-sitter-hl-face:keyword #<frame  georgezack@GZDELL 00000000053fddd0> (:inherit "#c586c0"))
  face-spec-set-2(tree-sitter-hl-face:keyword #<frame  georgezack@GZDELL 00000000053fddd0> (:inherit "#c586c0"))
  face-spec-recalc(tree-sitter-hl-face:keyword #<frame  georgezack@GZDELL 00000000053fddd0>)
  face-spec-set(tree-sitter-hl-face:keyword ((default :inherit font-lock-keyword-face)) face-defface-spec)
  custom-declare-face(tree-sitter-hl-face:keyword ((default :inherit font-lock-keyword-face)) "Face for keywords." :group tree-sitter-hl-faces)
  byte-code("\300\301!\210\302\303\304\305\306\301%\210\302\307\304\310\306\303%\210\311\312\313\314\306\307%\210\311\315\316\317\306\307%\210\311\320\321\322\306\307%\210\311\323\324\325\306\307..." [require tree-sitter custom-declare-group tree-sitter-hl nil "Syntax highlighting using tree-sitter." :group tree-sitter-hl-faces "Faces for highlighting code." custom-declare-face tree-sitter-hl-face:function ((default :inherit font-lock-function-name-face)) "Face for function declarations, definitions and bi..." tree-sitter-hl-face:function\.call ((default :inherit (link font-lock-function-name-face) :underline nil)) "Face for function calls." tree-sitter-hl-face:function\.builtin ((default :inherit font-lock-builtin-face)) "Face for builtin functions." tree-sitter-hl-face:function\.special ((default :inherit font-lock-preprocessor-face)) "Face for functions that alter things at compile/lo..." tree-sitter-hl-face:function\.macro ((default :inherit font-lock-preprocessor-face)) "Face for macro calls." tree-sitter-hl-face:method ((default :inherit tree-sitter-hl-face:function)) "Face for method declarations and definitions." tree-sitter-hl-face:method\.call ((default :inherit tree-sitter-hl-face:function\.call)) "Face for method invocations." put tree-sitter-hl-face:function\.method face-alias obsolete-face purecopy "0.9.0" t tree-sitter-hl-face:function\.method\.call tree-sitter-hl-face:type ((default :inherit font-lock-type-face)) "Face for types." tree-sitter-hl-face:type\.parameter ((default :inherit font-lock-variable-name-face)) "Face for type parameters." tree-sitter-hl-face:type\.argument ((default :inherit tree-sitter-hl-face:type)) "Face for type arguments." tree-sitter-hl-face:type\.builtin ((default :inherit font-lock-builtin-face)) ...] 8)
  require(tree-sitter-hl)

**Comment by ianyepan** [comment]
Thanks for reporting! Fixed in latest commit.
