### ISSUE TITLE
Inconsistent header-line border color in lsp-mode breadcrumb

### ISSUE THREAD

**Issue by YongJieYongJie** [ianpan870102/vscode-default-dark-emacs-theme#23]
### Issue:

In the header line, the border color for the words `common`, `loggers`, `loggers.go` and the character `>` is different from the color of the rest of the border (see top-left of screenshot below). FYI, the header is the breadcrumb from lsp-mode.

Question: *Is there a way to have a consistent border color across the header line?*

![image](https://user-images.githubusercontent.com/14101781/120091754-a24daf80-c140-11eb-987e-e519f73979f3.png)

Same situation occurs for the built-in manual:

![image](https://user-images.githubusercontent.com/14101781/120091849-3750a880-c141-11eb-9f95-92a42e262c1b.png)

### Expected behavior / look-and-feel:

Something that looks more natural might be like the Zenburn theme:

![image](https://user-images.githubusercontent.com/14101781/120091538-834e1e00-c13e-11eb-88f8-ab12f9754799.png)

**Comment by YongJieYongJie** [comment]
Update: I found this commit https://github.com/ianpan870102/vscode-dark-plus-emacs-theme/commit/1e694e1704e6bf55726040953ed5cf703f02c16d, will it help to solve the above issue?

**Comment by ianpan870102** [comment]
> Update: I found this commit 1e694e1, will it help to solve the above issue?

You're right, I think it's best to remove header-line declaration (and let it inherit mode-line) until I can find a better solution. Having header-line the same as mode-line is not as bad a thing as the screenshot you showed here, so fixing your problem is a higher priority.

**Comment by ianyepan** [comment]
> Update: I found this commit 1e694e1, will it help to solve the above issue?

I've made header-line look exactly like the mode-line, without inheriting it. This simultaneously fixes #23 and #10.

**Comment by ianyepan** [comment]
Wait, mode-line's background is way too much. I'll make it dark grey...

**Comment by ianyepan** [comment]
Looks good to me now

![image](https://user-images.githubusercontent.com/36686900/120094503-5821f980-c153-11eb-9bf5-75a4efe32a3a.png)

**Comment by YongJieYongJie** [comment]
@ianpan870102 Thanks for the amazingly fast fix! (And also the theme in the first place! :100:  )
