### ISSUE TITLE
Make color of org-code visually distinct from surrounding text

### ISSUE THREAD

**Issue by YongJieYongJie** [ianpan870102/vscode-default-dark-emacs-theme#24]
Currently font face for`org-code` (think of it like the org-mode equivalent of backticks in markdown) is set to `fg2`, and looks very similar to surrounding text:

![image](https://user-images.githubusercontent.com/14101781/126070562-de6a79ad-9e3b-4d49-b6a6-303345f44be0.png)

Perhaps change it to ms-orange:
![image](https://user-images.githubusercontent.com/14101781/126070584-0ebc8ac1-663b-4d61-a8b0-857f025eb24c.png)

Similar change can also be applied to org-verbatim, which affects lines like `=my inline verbatim quote=` (this concept is not in markdown, but it refers to any verbatim quote, not necessarily code).

org-code: https://github.com/ianyepan/vscode-dark-plus-emacs-theme/blob/master/vscode-dark-plus-theme.el#L175

fg2: https://github.com/ianyepan/vscode-dark-plus-emacs-theme/blob/master/vscode-dark-plus-theme.el#L65

ms-orange: https://github.com/ianyepan/vscode-dark-plus-emacs-theme/blob/master/vscode-dark-plus-theme.el#L100

**Comment by ianyepan** [comment]
This is a good idea! Please submit a PR and I'll merge it ASAP.

**Comment by YongJieYongJie** [comment]
@ianyepan PR created 👍

**Comment by ianyepan** [comment]
Looks good, thanks for the PR.
