### ISSUE TITLE
Current line number no longer "highlighted"

### ISSUE THREAD

**Issue by brownts** [ianpan870102/vscode-default-dark-emacs-theme#26]
It appears there was a change in commit https://github.com/ianyepan/vscode-dark-plus-emacs-theme/commit/231aaff15d572d52f601ce9b9275b9b16dbc2496 that now uses the same foreground color for both `line-number-current-line` and `line-number`.  This is not consistent with the VSCode Dark+ theme which differentiates the current line number from other line numbers using a different foreground color.

**Comment by ianyepan** [comment]
Thanks for bringing this up, I just pushed a commit that addressed this! Closing issue.
