### ISSUE TITLE
[Request] Support for diredfl

### ISSUE THREAD

**Issue by david-vicente** [ianpan870102/vscode-default-dark-emacs-theme#3]
When using [diredfl](https://github.com/purcell/diredfl) instead of adding colors to the fonts it adds colors to the background of the font.

**Comment by ianyepan** [comment]
Thanks for the feedback, I just added support for diredfl

![image](https://user-images.githubusercontent.com/36686900/83101891-ee0ce980-a0e5-11ea-9cce-ae3509c2e022.png)
