### ISSUE TITLE
Warnings on startup for setting attributes

### ISSUE THREAD

**Issue by cenedella** [ianpan870102/vscode-default-dark-emacs-theme#33]
Warning: setting attribute ‘:foreground’ of face ‘trailing-whitespace’: nil value is invalid, use ‘unspecified’ instead. 
Warning: setting attribute ‘:background’ of face ‘mode-line-buffer-id’: nil value is invalid, use ‘unspecified’ instead. 
Warning: setting attribute ‘:background’ of face ‘fringe’: nil value is invalid, use ‘unspecified’ instead.

**Comment by ianyepan** [comment]
Closed with https://github.com/ianyepan/vscode-dark-plus-emacs-theme/pull/34
