### ISSUE TITLE
Adding more images in Readme

### ISSUE THREAD

**Issue by innerout** [ianpan870102/vscode-default-dark-emacs-theme#4]
Hello Ian,
First of all congratulations for making this theme.

I would suggest you adding more images from popular Emacs modes your theme supports in order for interested users to have a better view of it. For example org-mode would be a good choice to display in the Readme.

You can take ideas on what images to capture by checking the Readme of the [spacemacs-theme](https://github.com/nashamri/spacemacs-theme).

**Comment by ianyepan** [comment]
Thanks for the suggestion, I just added some more screenshots
