### ISSUE TITLE
helm-selection 

### ISSUE THREAD

**Issue by kvaneesh** [ianpan870102/vscode-default-dark-emacs-theme#7]
Can we make the highlight better?  With the current values, I was finding it difficult to locate the current line.

**Comment by ianyepan** [comment]
Hi and thanks for the feedback @kvaneesh , do you mind posting a screenshot to illustrate the problem?

**Comment by kvaneesh** [comment]
`(helm-selection                           ((,class (:background ,bg-hl :underline nil))))
   `(helm-selection-line                      ((,class (:background ,bg-hl))))
 
That change made it better

**Comment by kvaneesh** [comment]
![image](https://user-images.githubusercontent.com/19270/84149751-91fb7b00-aa7e-11ea-9881-de214b87331c.png)

**Comment by kvaneesh** [comment]
with the changes suggested 
![image](https://user-images.githubusercontent.com/19270/84149976-df77e800-aa7e-11ea-80cd-52fa3663fcfc.png)

**Comment by ianyepan** [comment]
Thanks man! It was indeed meant to be `bg-hl`, I must have missed it when renaming the variables.
I'll push a commit to update this change

**Comment by ianyepan** [comment]
This commit https://github.com/ianpan870102/vscode-dark-plus-emacs-theme/commit/9b0089670244d2d60f2eae4287e15cc8a3310c29 should fix the issue
