### ISSUE TITLE
Is there any intent to port the light theme too?

### ISSUE THREAD

**Issue by tareefdev** [ianpan870102/vscode-default-dark-emacs-theme#8]

**Comment by ianyepan** [comment]
Good question, I've thought about that. Perhaps I would in the future. If so I'd remember to announce it on r/emacs Reddit, and also link it here in the README.

**Comment by tareefdev** [comment]
Thanks for your incredible work on this theme. I really enjoy using it.

**Comment by ianyepan** [comment]
@tareefdev thanks for the kind words man, glad you liked it!
